### ISSUE TITLE
Request: allow a different 1/1 reference frequency

### ISSUE THREAD

**Issue by wolftune** [ibancg/lingot#25]
I can load a scala file, but it always treats 1/1 as C (or seems to). I have reasons to want to have a different pitch, like D or A be the reference point. It would be nice if that could be an option somehow.

**Comment by ibancg** [comment]
@alignwaivers also raised his concern in #28 :

`Still not sure why the default base value is assumed to be middle C though, is there a reason for this?
`

Sorry, I overlooked this issue, because I did not understand it completely at the beginning.

The way I see it, it is possible to use another pitch as the "base value" to start building the scale from it. Find below an example with a pentatonic scale built from _A440_, which I (maybe wrongly) called _"mid-A"_:

![image](https://user-images.githubusercontent.com/5263631/72226437-81a7a880-3591-11ea-9951-a3c5a82c4d3b.png)

If you have a scala file whose first note is supposed to be, say, A440, you can just load it and manually replace the name **and frequency** of the first note, and all the other frequencies will shift accordingly.

Does this fix your issue? maybe I am missing something here, do you see a better way of doing this?

**Comment by wolftune** [comment]
I just didn't realize that the Frequency could just be edited already. It wasn't obvious I could just type it in, but there it is. It works already perfectly!

I literally just double click on "mid-A" and type in something else like "587.330" and indeed everything else adjusts appropriately.
