### ISSUE TITLE
Request: support names from scala files

### ISSUE THREAD

**Issue by wolftune** [ibancg/lingot#26]
For example. this is the Kite guitar scala file that has comments with names after the cents:

```
! 41-edo.scl
!
41-edo by Kite Giedraitis August 2019
 41
!
29.26829	^D
58.53659	^^D/vEb
87.80488	vD#/Eb
117.07317	D#/^Eb
146.34146	^D#/vvE
175.60976	vE
204.87805	E
234.14634	^E
263.41463	vF
292.68293	F
321.95122	^F
351.21951	^^F/vGb
380.48780	vF#/Gb
409.75610	F#/^Gb
439.02439	^F#/vvG
468.29268	vG
497.56098	G
526.82927	^G
556.09756	^^G/vAb
585.36585	vG#/Ab
614.63415	G#/^Ab
643.90244	^G#/vvA
673.17073	vA
702.43902	A
731.70732	^A
760.97561	^^A/vBb
790.24390	vA#/Bb
819.51220	A#/^Bb
848.78049	^A#/vvB
878.04878	vB
907.31707	B
936.58537	^B
965.85366	vC
995.12195	C
1024.39024	^C
1053.65854	^^C/vDb
1082.92683	vC#/Db
1112.19512	C#/^Db
1141.46341	^C#/vvD
1170.73171	vD
1200.00000	D
```

It would be great if LINGOT could recognize the names and use those rather than have to be manually input.

If there's a current way or different file format to make this work, please let me know.

**Comment by ibancg** [comment]
Yes we can certainly try that.

I [started a branch](https://github.com/ibancg/lingot/tree/26-support-names-from-scala-files) which can read those names, but it does not support special characters like spaces, tabs, '`=`', ...

If you could test it on your scale files it would be great.

Do you have a link to more of those scales with names? otherwise we can go like this.

**Comment by alignwaivers** [comment]
I was able to build your version, but the default after downloading https://github.com/ibancg/lingot/tree/26-support-names-from-scala-files didn't work. I had to checkout to origin/26-support-names-from-scala before it worked?

The good news is the names showed up! So it definitely works (except for middle-c which showed up as having the name of 1, which is clearly due to the .scl file itself)

Thanks for having implemented that feature @ibancg !

**Comment by alignwaivers** [comment]
@ibancg realized there's an issue with the display and the spread is +/- 50. Makes it pretty much unusable. Is there a way to update this?

![image](https://user-images.githubusercontent.com/26056586/69924328-b3d8cd00-145f-11ea-9c09-313dfc0c6278.png)

**Comment by ibancg** [comment]
We can close this issue. The issue about the needle spread has been moved to #28.
